
server:
  port: 8080

spring:
  datasource:


    url: ${db.url}
    username:  ${db.username}
    password:  ${db.password}
    driver-class-name: org.postgresql.Driver




#
#    url: jdbc:postgresql://localhost:5432/eventeasedb
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver


  mail:
    host:  smtp.gmail.com
    port: 587
    username: ${user.email}
    password: ${user.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


    servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





security:
  jwt:
    jwtSigningKey: ${secret.Key}



  devtools:
    livereload:
      enabled: true
