
server:
  port: 8080

spring:
  datasource:
    url: ${dburl}
    username:  ${dbUsername}
    password:  ${dbPassword}
    driver-class-name: org.postgresql.Driver

#
#    url: jdbc:postgresql://localhost:5432/eventeasedb
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver

  mail:
    host:  smtp.gmail.com
    port: 587
    username: ${userEmail}
    password: ${userPassword}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



security:
  jwt:
    jwtSigningKey: ${secretKey}




  devtools:
    livereload:
      enabled: true

app:
  url: ${appUrl}



springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs


  cache:
    type: caffeine
    cache-names: bucket4j-cache

#
#
#bucket4j:
#  enabled: true
#  filters:
#    - cache-name: bucket4j-cache
#      url: .*
#      http-status-code: TOO_MANY_REQUESTS
#      http-response-body: "{ \"error\": true, \"message\": \"You have exhausted your API Request Quota\" }"
#      rate-limits:
#        - cache-key: getRemoteAddr()
#          bandwidths:
#            - capacity: 100
#              time: 1
#              unit: minutes


bucket4j:
  enabled: true
  filters:
    - cache-name: bucket4j-cache
      url: .*
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "{ \"error\": true, \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 100
              time: 1
              unit: minutes

